name: D

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest 
            arch: amd64
            compiler: ldc-master
          - os: ubuntu-24.04-arm 
            arch: arm64
            compiler: ldc-master
          - os: macos-latest
            arch: arm64
            compiler: ldc-master
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{matrix.compiler}}
      - name: (Dub) Build
        run: dub build -v
      - name: Run fib32.wasm
        run: dub :fib32
